# Default values for polygon-etl-streaming.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

config:
  PROVIDER_URI: "http://user:pass@localhost:8332"
  STREAM_OUTPUT: "projects/<your-project>/topics/crypto_polygon"
  GCS_PREFIX: "gs://<your-bucket>/polygon-etl/streaming"
  LAG_BLOCKS: "10"
  MAX_WORKERS: "20"
  ENTITY_TYPES: ""
  BATCH_SIZE: "2"
  BLOCK_BATCH_SIZE: "20"

lsb_file: last_synced_block.txt
lsb_path: /var/polygon-etl
pid_file: stream.pid

init:
  image:
    repository: google/cloud-sdk
    tag: 292.0.0-alpine
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
stream:
  image:
    repository: blockchainetl/polygon-etl
    tag: 0.2.0
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "2048Mi"
      cpu: "350m"
  env:
    LAST_SYNCED_BLOCK_FILE_MAX_AGE_IN_SECONDS: "600"
  livenessProbe:
    initialDelaySeconds: "300"
    periodSeconds: "300"

upload:
  image:
    repository: google/cloud-sdk
    tag: 292.0.0-alpine
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

securityContext: {}
#  runAsUser: 1000
#  runAsGroup: 1000
#  fsGroup: 1000

nodeSelector: {}

tolerations: []

affinity: {}
