stream:
  image:
    repository: blockchainetl/polygon-etl
    tag: 0.3.4
config:
  PROVIDER_URI: "grpcs://api.mainnet.polygon.one:443"
  STREAM_OUTPUT: "projects/<your_project>/topics/crypto_polygon"
  GCS_PREFIX: "gs://<your_bucket>/polygon-etl/streaming"
  LAG_BLOCKS: "10"
  ENTITY_TYPES: "block,transaction,log,token_transfer,trace,contract,token"
  BATCH_SIZE: "2"
  BLOCK_BATCH_SIZE: "20"
  MAX_WORKERS: "20"
